# Streamlit configuration for the Climate AI Dashboard

[server]
headless = true
port = 8503
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#00ffff"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#ffffff"

[browser]
gatherUsageStats = false