# Example secrets file for Streamlit Cloud deployment
# Copy this to .streamlit/secrets.toml and fill in your actual API keys

OPENWEATHER_API_KEY = "your_openweather_api_key_here"
AQICN_API_KEY = "your_aqicn_api_key_here"

# Email configuration (optional)
EMAIL_ADDRESS = "your_email@gmail.com"
EMAIL_PASSWORD = "your_app_password"
RECIPIENT_EMAIL = "alerts@yourdomain.com"

# Twilio configuration (optional)
TWILIO_ACCOUNT_SID = "your_twilio_account_sid"
TWILIO_AUTH_TOKEN = "your_twilio_auth_token"
TWILIO_PHONE_FROM = "+1234567890"
TWILIO_PHONE_TO = "+0987654321"